version: '2'
services:
  servicenet-app:
    image: servicenet
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      # You can find the host ip by running: "ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/ServiceNet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_MONGODB_URI=mongodb://servicenet-mongo:27017/serviceNet
  servicenet-mongo:
    extends:
      file: mongo.yml
      service: servicenet-mongo
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
