version: '2'
services:
    servicenet-app:
        image: servicenet
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://servicenet-postgresql:5432/ServiceNet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    servicenet-postgresql:
        extends:
            file: postgresql.yml
            service: servicenet-postgresql
